import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated by Astu students
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/signup" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Signup
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/signin" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SignIn
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/resetpassword" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ResetPassword
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/buydetailpage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Buydetailpage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homebuy" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomeBuy
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homerent" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomeRent
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/rentdetailpage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Rentdetailpage
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;